services:
  - type: web
    name: eden-app
    env: docker
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_LOG_LEVEL
        value: debug
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: eden-db
          property: connectionString

databases:
  - name: eden-db
    plan: free
    databaseName: eden
    user: eden
